image: bradrydzewski/python:2.7
script:
  - pip install tox
  - tox
deploy:
  git:
    target: ssh://git@deis.173.247.105.8.xip.io:2222/gifted-hardtack.git
    branch: master
    force: false
notify:
  slack:
    webhook_url: $$slack_url
    on_started: true
    on_success: true
    on_failure: true
